In [3]:
import numpy as np

# Create a Python list
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

print(my_array) 

[1 2 3 4 5]


In [5]:
import numpy as np

# Create an array of 5 zeros
my_array = np.zeros(5)

print(my_array) 

[0. 0. 0. 0. 0.]


In [6]:
import numpy as np

# Create an array of 5 ones
my_array = np.ones(5)

print(my_array)

[1. 1. 1. 1. 1.]


In [7]:
import numpy as np

# Create an array from 0 to 10 with a step size of 2
my_array = np.arange(0, 10, 2)

print(my_array) 

[0 2 4 6 8]


In [8]:
import numpy as np

# Create an array from 0 to 10 with 5 evenly spaced values
my_array = np.linspace(0, 10, 5)

print(my_array)

[ 0.   2.5  5.   7.5 10. ]


In [9]:
import numpy as np

# Create an array
my_array = np.array([1, 2, 3, 4, 5])

# Access the first element
print(my_array[0])  # Output: 1

# Access the last element
print(my_array[-1])  # Output: 5

# Access a subset of elements (slicing)
print(my_array[1:3])

1
5
[2 3]
