In [10]:
# Universal Functions (ufuncs)
# Element-wise operations like np.add(), np.subtract(), np.multiply(), np.divide().


import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Addition
result = np.add(array1, array2)
print(result)  

[ 7  9 11 13 15]


In [11]:
# Subtraction
result = np.subtract(array1, array2)
print(result) 

[-5 -5 -5 -5 -5]


In [12]:
# Multiplication
result = np.multiply(array1, array2)
print(result) 

[ 6 14 24 36 50]


In [13]:
# Division
result = np.divide(array1, array2)
print(result)  

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [15]:
# Statistical Functions
# Calculating mean, median, standard deviation, variance, minimum, and maximum values.


import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Mean
result = np.mean(array)
print(result) 

3.0


In [16]:
# Median
result = np.median(array)
print(result) 

3.0


In [17]:
# Standard Deviation
result = np.std(array)
print(result)  

1.4142135623730951


In [18]:
# Variance
result = np.var(array)
print(result)  

2.0


In [19]:
# Minimum
result = np.min(array)
print(result) 

1


In [20]:
# Maximum
result = np.max(array)
print(result) 

5


In [22]:
# Linear Algebra Functions
# Performing operations like matrix multiplication, inversion, and eigenvalue decomposition.


import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix Multiplication
result = np.dot(matrix1, matrix2)
print(result)


[[19 22]
 [43 50]]


In [23]:
# Matrix Inversion
result = np.linalg.inv(matrix1)
print(result)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [25]:
# Eigenvalue Decomposition
eigenvalues, eigenvectors = np.linalg.eig(matrix1)
print(eigenvalues)
# Output: [-0.37228132  5.37228132]
print(eigenvectors)


[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
