In [1]:
# Checking Array Dimensions
import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Get the shape of the array
print(array.shape) 

(2, 3)


In [2]:
# Get the number of dimensions
print(array.ndim)  

2


In [3]:
# Changing Array Shape

import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to 2D
new_array = array.reshape(2, 3)
print(new_array)

[[1 2 3]
 [4 5 6]]


In [4]:
# Flatten
# Flatten a multi-dimensional array to a 1D array.


import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Flatten the array
new_array = array.flatten()
print(new_array) 


[1 2 3 4 5 6]


In [5]:
# Transpose
# Swap the axes of a multi-dimensional array.


import numpy as np

# Create a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Transpose the array
new_array = array.transpose()
print(new_array)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
# # Concatenating and Splitting Arrays
# Using np.concatenate(), np.vstack(), np.hstack(), and np.split() functions to concatenate and split arrays.

# Concatenate
# Concatenate two or more arrays along a specified axis.


import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate the arrays
new_array = np.concatenate((array1, array2))
print(new_array) 

[1 2 3 4 5 6]


In [7]:
# Vertical Stack
# Stack two or more arrays vertically.


import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays vertically
new_array = np.vstack((array1, array2))
print(new_array)

[[1 2 3]
 [4 5 6]]


In [8]:
# Horizontal Stack
# Stack two or more arrays horizontally.


import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Stack the arrays horizontally
new_array = np.hstack((array1, array2))
print(new_array)

[1 2 3 4 5 6]


In [9]:
# Split
# Split an array into multiple sub-arrays along a specified axis.


import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6])

# Split the array into two sub-arrays
new_arrays = np.split(array, 2)
print(new_arrays)  


[array([1, 2, 3]), array([4, 5, 6])]
