In [1]:
# Random Number Generation

# Generating random numbers using np.random.


import numpy as np

# Generate a random integer between 0 and 10
random_int = np.random.randint(0, 11)
print(random_int)

# Generate a random float between 0 and 1
random_float = np.random.rand()
print(random_float)

# Generate an array of 5 random floats between 0 and 1
random_array = np.random.rand(5)
print(random_array)

0
0.05940837768210039
[0.75338212 0.42384761 0.15114879 0.57203973 0.59462601]


In [2]:
# Seeding Random Number Generation

# Seeding random number generation using np.random.seed().


import numpy as np

# Set the seed for random number generation
np.random.seed(0)

# Generate a random integer between 0 and 10
random_int = np.random.randint(0, 11)
print(random_int)

# Generate a random float between 0 and 1
random_float = np.random.rand()
print(random_float)

# Generate an array of 5 random floats between 0 and 1
random_array = np.random.rand(5)
print(random_array)

5
0.8442657485810173
[0.85794562 0.84725174 0.6235637  0.38438171 0.29753461]


In [3]:
# Random Sampling

# Randomly sampling elements from an array using np.random.choice().


import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Randomly sample 3 elements from the array
random_sample = np.random.choice(array, 3, replace=False)
print(random_sample)

[2 3 4]


In [4]:
# Shuffling and Permutations

# Shuffling and generating permutations of an array using np.random.shuffle() and np.random.permutation().


import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5])

# Shuffle the array
np.random.shuffle(array)
print(array)

# Generate a permutation of the array
permutation = np.random.permutation(array)
print(permutation)

[5 1 4 3 2]
[5 4 3 2 1]
