In [1]:
import numpy as np

# Create two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Addition
result = array1 + array2
print(result)  

[ 7  9 11 13 15]


In [2]:
# substraction
result = array1 - array2
print(result)  

[-5 -5 -5 -5 -5]


In [3]:
# Multiplication
result = array1 * array2
print(result)  

[ 6 14 24 36 50]


In [4]:
# Division
result = array1 / array2
print(result)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
# BROADCASTING
import numpy as np

# Create two arrays with different shapes
array1 = np.array([1, 2, 3])
array2 = np.array([4])

# Addition
result = array1 + array2
print(result) 

[5 6 7]


In [7]:
# Multiplication
result = array1 * array2
print(result)

[ 4  8 12]


In [10]:
# ELEMENT WISE OPERATIONS AND FUNCTIONS
import numpy as np

# Create an array
array = np.array([1, 4, 9, 16, 25])

# Square root
result = np.sqrt(array)
print(result)

[1. 2. 3. 4. 5.]


In [9]:
# Sine
result = np.sin(array)
print(result) 

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [11]:
# Exponential
result = np.exp(array)
print(result)  

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
